name: Build & Deploy BN_ATI Report

on:
  workflow_dispatch:
  schedule:
    - cron: "22 6 * * *"
  push:
    paths:
      - BN_ATI_REPORT/**
      - .github/workflows/action_bn_ati.yml

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: BN_ATI_REPORT

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Build report
        run: python scripts/build_report.py

      - name: Ensure .nojekyll
        run: |
          touch docs/.nojekyll

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # path is from the repository root; keep it explicit
          path: BN_ATI_REPORT/docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
      - name: Commit generated files (optional)
        run: |
          if [[ -n "$(git status --porcelain docs)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/report.json docs/index.html
            git commit -m "Update BN_ATI report ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
            git push
          fi
