# .github/workflows/action_bn_ati.yml
name: Build & Deploy BN_ATI Report

on:
  workflow_dispatch:
  schedule:
    - cron: "22 6 * * *"  # daily at 06:22 UTC
  push:
    paths:
      - BN_ATI_REPORT/**
      - .github/workflows/action_bn_ati.yml

# IMPORTANT: allow pushing commits + deploying Pages
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: BN_ATI_REPORT

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # keep credentials so `git push` uses GITHUB_TOKEN
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Build report (writes to BN_ATI_REPORT/docs)
        run: python scripts/build_report.py

      - name: Ensure .nojekyll
        run: touch docs/.nojekyll

      # OPTIONAL: commit generated files for history
      - name: Commit generated files (optional)
        run: |
          # rebase in case the branch moved
          git pull --rebase origin "${GITHUB_REF_NAME}"
          if [[ -n "$(git status --porcelain docs)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/report.json docs/index.html docs/.nojekyll
            git commit -m "BN_ATI report update ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
            git push
          fi

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # path from repo root (not affected by working-directory)
          path: BN_ATI_REPORT/docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
