# .github/workflows/action_bn_ati.yml
name: Build BN_ATI Report

on:
  workflow_dispatch:
  schedule:
    - cron: "22 6 * * *"
  push:
    paths:
      - BN_ATI_REPORT/**
      - .github/workflows/action_bn_ati.yml

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: BN_ATI_REPORT
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # optional: cache pip
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Build report (CSV → JSON/HTML)
        run: |
          python scripts/build_report.py

      - name: Commit artifacts
        run: |
          if [[ -n "$(git status --porcelain docs)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/report.json docs/index.html
            git commit -m "BN_ATI report update ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
            git push
          fi
