name: Build BN data report

on:
  workflow_dispatch:
  schedule:
    - cron: "22 6 * * *"  # daily 06:22 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: BN_ATI_REPORT
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Build report
        env:
          CKAN_BASE: https://open.canada.ca/data/en
        run: |
          python scripts/build_report.py

      - name: Commit artifacts
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/report.json docs/schemas/
            git commit -m "Update report.json"
            git push
          fi
